apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: project-deployment
  namespace: development
  labels:
    app: project-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        apps: project
    spec:
      containers:
      - name: project
        ports:
        - containerPort: 8081
